SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
USE [$(DBName)];
GO
IF OBJECT_ID(N'[dbo].[vw_WaitStats_Current]', N'V') IS NOT NULL DROP VIEW [dbo].[vw_WaitStats_Current];
GO
CREATE VIEW [dbo].[vw_WaitStats_Current]
AS
SELECT
    wait_type,
    waiting_tasks_count,
    wait_time_ms,
    max_wait_time_ms,
    signal_wait_time_ms
FROM sys.dm_os_wait_stats
WHERE wait_type NOT IN (
    'SLEEP_TASK','BROKER_TASK_STOP','BROKER_TO_FLUSH','SQLTRACE_BUFFER_FLUSH',
    'CLR_SEMAPHORE','LAZYWRITER_SLEEP','RESOURCE_QUEUE','REQUEST_FOR_DEADLOCK_SEARCH',
    'XE_TIMER_EVENT','XE_DISPATCHER_JOIN','FT_IFTS_SCHEDULER_IDLE_WAIT',
    'WAITFOR','LOGMGR_QUEUE','CHECKPOINT_QUEUE','BROKER_EVENTHANDLER',
    'TRACEWRITE','WAITFOR_TASK','DISPATCHER_QUEUE_SEMAPHORE','FT_IFTSHC_MUTEX',
    'BROKER_RECEIVE_WAITFOR','REPUBLISH_QUEUE','PREEMPTIVE_OS_GETPROCADDRESS',
    'PREEMPTIVE_OS_AUTHENTICATIONOPS'
);
GO